name = "TestItemDetection"
uuid = "76b0de8b-5c4b-48ef-a724-914b33ca988d"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "1.1.1-DEV"

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JuliaSyntax = "0.4"
julia = "1"

[targets]
test = ["Test", "TestItemRunner"]
